"""add streaming available

Revision ID: e393d492a60a
Revises: 39cac53c7136
Create Date: 2025-07-03 03:18:56.061797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e393d492a60a'
down_revision = '39cac53c7136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('streaming_available', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'streaming_available')
    # ### end Alembic commands ###
